### ISSUE TITLE
Can Html5VideoPipeline support audio(AAC) from audio device

### ISSUE THREAD

**Issue by touchsky2018** [AxisCommunications/media-stream-library-js#664]
Can Html5VideoPipeline support audio(AAC) from audio device

There is a error when live audio with Html5VideoPipeline 
Is that a bug? or any misstake in source?

-------------version-----------
10.4.1

--------------error------------------
media-stream-library.min.js:2 closing socket due to incoming error RangeError: "value" argument is out of bounds
    at B (:4200/vendor.js:39070:37)
    at Uint8Array.u.writeUint16BE.u.writeUInt16BE (:4200/vendor.js:39226:41)
    at Ie.copy (:4200/vendor.js:45456:15)
    at Me.copy (:4200/vendor.js:45934:59)
    at De.copy (:4200/vendor.js:45934:59)
    at De.copy (:4200/vendor.js:45934:59)
    at De.copy (:4200/vendor.js:45934:59)
    at De.copy (:4200/vendor.js:45934:59)
    at De.copy (:4200/vendor.js:45934:59)
    at De.copy (:4200/vendor.js:45934:59)

-------------source------------------

<video #audio autoplay controls="controls"></video>

  playAudio() {
    var that = this;

    // Grab a reference to the video element
    const mediaElement3 = that.audio.nativeElement;

    // Setup a new pipelineserver
    this.pipeline3 = new pipelines.Html5VideoPipeline({
      ws: { uri: this.wsServer, timeout: 60000 },
      rtsp: { uri: this.rtspServer3 },
      mediaElement: mediaElement3
    })

    // Restart stream on RTCP BYE (stream ended)
    this.pipeline3.rtsp.onRtcp = (rtcp: any) => {
      if (isRtcpBye(rtcp)) {
        console.log("---pipeline3.rtcp.bye");
        setTimeout(() => {
          that.playAudio();
        }, 0)
      }
    }

    this.pipeline3.rtsp.onError = (err: RTSPResponseError) => {
      console.log("---pipeline3.rtsp.onError--" + err.code + "--" + err.message);
    }

    this.pipeline3.ready.then(() => {
      that.pipeline3.rtsp.play();
      console.log("---pipeline3.rtsp.play");
    })
    .catch((err: any) => {
      console.log("rtsp error:" + err);
      this.pipeline3 && this.pipeline3.close();
    })
  }

**Comment by steabert** [comment]
Possibly mitigated by #769
